version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homecare
    ports:
      - "5432:5432"
    volumes:
      - homecare_pg_data:/var/lib/postgresql/data
volumes:
  homecare_pg_data:
    driver: local
