name: backend
version: 1.0.0
publish_to: "none"
description: Simple Shelf backend for authentication

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path: ^1.9.0
  bcrypt: ^2.0.2
  dart_jsonwebtoken: ^2.10.4
  dotenv: ^4.2.0
  postgres: ^3.2.1
  uuid: ^4.4.0
  qr: ^3.0.1
  shelf_web_socket: ^1.0.4

dev_dependencies:
  test: ^1.25.2
