name: backend
version: 1.0.0
publish_to: "none"
description: Simple Shelf backend for authentication

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  path: ^1.9.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^3.3.1
  dotenv: ^4.2.0
  postgres: ^3.2.1
  uuid: ^4.4.0
  qr: ^3.0.1
  shelf_web_socket: ^3.0.0

  web_socket_channel: any
dev_dependencies:
  test: ^1.25.2
  async: any
  stream_channel: any

