name: homecare_backend
description: Utilities for the Homecare backend infrastructure.
version: 0.1.0
publish_to: "none"

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dotenv: ^4.2.0
  path: ^1.8.3
  postgres: ^2.6.1

dev_dependencies:
  lints: ^3.0.0
