name: Flutter CI

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/flutter-ci.yml'
  pull_request:
    paths:
      - 'app/**'
      - '.github/workflows/flutter-ci.yml'

jobs:
  flutter:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Cache pub packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            app/.dart_tool
          key: ${{ runner.os }}-flutter-${{ hashFiles('app/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: app/build/app/outputs/flutter-apk/app-debug.apk
